language: node_js
node_js:
    - "4.4.2"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libfontconfig

install:
    - npm install
    - npm install bower
    - node_modules/.bin/bower install --config.interactive=false

script:
    - node_modules/.bin/gulp test
